
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: recep
      POSTGRES_PASSWORD: R12345678
      POSTGRES_DB: new
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "7474:3000"  
    depends_on:
      - db
    volumes:
      - ./frontend:/usr/src/app/frontend  
      - ./kayitlar:/usr/src/app/kayitlar

volumes:
  db_data:

